import nltk
import string
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')


def preprocess_text(sentence):
    sentence = sentence.translate(str.maketrans("", "", string.punctuation))
    sentence = sentence.lower()
    words = word_tokenize(sentence)
    stop_words = set(stopwords.words('portuguese'))
    words = [word for word in words if word not in stop_words]
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    sentence = ''.join(words)
    return sentence


train_data = [
    ('Este restaurante é maravilhoso', '1'),
    ('O clima hoje está perfeito', '1'),
    ('Adorei a música que tocou', '1'),
    ('Minhas férias foram incríveis', '1'),
    ('Ela é uma amiga incrível', '1'),
    ('O por do sol é lindo', '1'),
    ('A comida estava deliciosa', '1'),
    ('O livro é inspirador', '1'),
    ('O abraço dela me faz bem', '1'),
    ('Eu ganhei na loteria!', '1'),
    ('Este filme é espetacular', '1'),
    ('A festa foi sensacional', '1'),
    ('Eu me sinto muito feliz hoje', '1'),
    ('A aula foi muito produtiva', '1'),
    ('Ele é um gênio', '1'),
    ('A natureza é incrível', '1'),
    ('A equipe ganhou o jogo', '1'),
    ('A arte é fascinante', '1'),
    ('O bolo está delicioso', '1'),
    ('O novo carro é impressionante', '1'),
    ('A apresentação foi incrível', '1'),
    ('O espetáculo foi emocionante', '1'),
    ('Ela é uma pessoa adorável', '1'),
    ('Estou apaixonado por você', '1'),
    ('Esta viagem foi inesquecível', '1'),
    ('O dia do casamento foi perfeito', '1'),
    ('A vista da montanha é deslumbrante', '1'),
    ('O sorvete é uma delícia', '1'),
    ('A noite estrelada é linda', '1'),
    ('A surpresa foi maravilhosa', '1'),
    ('A reunião foi muito produtiva', '1'),
    ('O pôr do sol é espetacular', '1'),
    ('A música me tocou profundamente', '1'),
    ('O presente foi emocionante', '1'),
    ('Este lugar é mágico', '1'),
    ('Ela é uma pessoa inspiradora', '1'),
    ('O show foi fenomenal', '1'),
    ('O amor é maravilhoso', '1'),
    ('O parque é encantador', '1'),
    ('O livro é cativante', '1'),
    ('A comida é divina', '1'),
    ('O filme é envolvente', '1'),
    ('O nascer do sol é espetacular', '1'),
    ('Este jogo é viciante', '1'),
    ('A viagem foi surpreendente', '1'),
    ('O encontro foi maravilhoso', '1'),
    ('A amizade é incrível', '1'),
    ('O espetáculo é emocionante', '1'),
    ('Ela é uma pessoa excepcional', '1'),
    ('Estou me sentindo abençoado', '1'),
    ('O resultado foi espetacular', '1'),
    ('A notícia é empolgante', '1'),
    ('A descoberta é incrível', '1'),
    ('O talento dele é surpreendente', '1'),
    ('O piquenique foi maravilhoso', '1'),
    ('O sorriso dela é contagiante', '1'),
    ('O dia foi incrivelmente produtivo', '1'),
    ('O filme é hilariante', '1'),
    ('O jogo foi emocionante', '1'),
    ('O parque de diversões é sensacional', '1'),
    ('A apresentação foi cativante', '1'),
    ('O concerto foi espetacular', '1'),
    ('O resultado da competição foi empolgante', '1'),
    ('A inovação é incrível', '1'),
    ('O novo aplicativo é viciante', '1'),
    ('A coleção é deslumbrante', '1'),
    ('O esforço valeu a pena', '1'),
    ('A viagem foi incrivelmente inspiradora', '1'),
    ('A conquista é sensacional', '1'),
    ('A surpresa foi incrível', '1'),
    ('O jantar foi delicioso', '1'),
    ('O por do sol é magnífico', '1'),
    ('A música é envolvente', '1'),
    ('O espetáculo é empolgante', '1'),
    ('O novo restaurante é excepcional', '1'),
    ('O bolo é uma tentação', '1'),
    ('A exposição é fenomenal', '1'),
    ('O filme é hilariante', '1'),
    ('O jogo foi emocionante', '1'),
    ('O parque de diversões é sensacional', '1'),
    ('A apresentação foi cativante', '1'),
    ('O concerto foi espetacular', '1'),
    ('O resultado da competição foi empolgante', '1'),
    ('A inovação é incrível', '1'),
    ('O novo aplicativo é viciante', '1'),
    ('A coleção é deslumbrante', '1'),
    ('O esforço valeu a pena', '1'),
    ('A viagem foi incrivelmente inspiradora', '1'),
    ('A conquista é sensacional', '1'),
    ('A surpresa foi incrível', '1'),
    ('O jantar foi delicioso', '1'),
    ('O por do sol é magnífico', '1'),
    ('A música é envolvente', '1'),
    ('O espetáculo é empolgante', '1'),
    ('O novo restaurante é excepcional', '1'),
    ('O bolo é uma tentação', '1'),
    ('A exposição é fenomenal', '1'),
    ('O livro é instigante', '1'),
    ('A comida é sensacional', '1'),
    ('O filme é espetacular', '1'),
    ('O presente foi emocionante', '1'),
    ('Este lugar é incrível', '1'),
    ('A equipe é excepcional', '1'),
    ('O livro é incrivelmente inspirador', '1'),
    ('A paisagem é deslumbrante', '1'),
    ('O almoço foi maravilhoso', '1'),
    ('A peça de teatro foi emocionante', '1'),
    ('O esforço foi recompensado', '1'),
    ('A surpresa foi inesperada', '1'),
    ('O passeio foi divertido', '1'),
    ('A vista da montanha é espetacular', '1'),
    ('O sorvete é delicioso', '1'),
    ('A noite foi memorável', '1'),
    ('A viagem foi transformadora', '1'),
    ('O dia do casamento foi mágico', '1'),
    ('O nascer do sol é deslumbrante', '1'),
    ('A música me faz dançar', '1'),
    ('O presente foi surpreendente', '1'),
    ('A reunião foi produtiva', '1'),
    ('O pôr do sol é incrível', '1'),
    ('A apresentação foi envolvente', '1'),
    ('O espetáculo foi arrebatador', '1'),
    ('Ela é uma pessoa incrível', '1'),
    ('Estou me sentindo inspirado', '1'),
    ('O resultado foi surpreendente', '1'),
    ('A notícia é emocionante', '1'),
    ('A descoberta é incrível', '1'),
    ('O talento dele é notável', '1'),
    ('O piquenique foi memorável', '1'),
    ('O sorriso dela é cativante', '1'),
    ('O dia foi extremamente produtivo', '1'),
    ('A vista da montanha é impressionante', '1'),
    ('O sorvete é tentador', '1'),
    ('A noite estrelada é mágica', '1'),
    ('A surpresa foi inesquecível', '1'),
    ('A reunião foi altamente produtiva', '1'),
    ('O pôr do sol é espetacular', '1'),
    ('A música me toca profundamente', '1'),
    ('O presente foi emocionante', '1'),
    ('Este lugar é mágico', '1'),
    ('Ela é uma pessoa inspiradora', '1'),
    ('O show foi fenomenal', '1'),
    ('O amor é maravilhoso', '1'),
    ('O parque é encantador', '1'),
    ('O livro é cativante', '1'),
    ('A comida é divina', '1'),
    ('O filme é envolvente', '1'),
    ('O nascer do sol é espetacular', '1'),
    ('Este jogo é viciante', '1'),
    ('A viagem foi surpreendente', '1'),
    ('O encontro foi maravilhoso', '1'),
    ('A amizade é incrível', '1'),
    ('O espetáculo é emocionante', '1'),
    ('Ela é uma pessoa excepcional', '1'),
    ('Estou me sentindo abençoado', '1'),
    ('O resultado foi espetacular', '1'),
    ('A notícia é empolgante', '1'),
    ('A descoberta é incrível', '1'),
    ('O talento dele é surpreendente', '1'),
    ('O piquenique foi maravilhoso', '1'),
    ('O sorriso dela é contagiante', '1'),
    ('O dia foi incrivelmente produtivo', '1'),
    ('O filme é hilariante', '1'),
    ('O jogo foi emocionante', '1'),
    ('O parque de diversões é sensacional', '1'),
    ('A apresentação foi cativante', '1'),
    ('O concerto foi espetacular', '1'),
    ('O resultado da competição foi empolgante', '1'),
    ('A inovação é incrível', '1'),
    ('O novo aplicativo é viciante', '1'),
    ('A coleção é deslumbrante', '1'),
    ('O esforço valeu a pena', '1'),
    ('A viagem foi incrivelmente inspiradora', '1'),
    ('A conquista é sensacional', '1'),
    ('A surpresa foi incrível', '1'),
    ('O jantar foi delicioso', '1'),
    ('O por do sol é magnífico', '1'),
    ('A música é envolvente', '1'),
    ('O espetáculo é empolgante', '1'),
    ('O novo restaurante é excepcional', '1'),
    ('O bolo é uma tentação', '1'),
    ('A exposição é fenomenal', '1'),
    ('O livro é instigante', '1'),
    ('A comida é sensacional', '1'),
    ('O filme é espetacular', '1'),
    ('O presente foi emocionante', '1'),
    ('Este lugar é incrível', '1'),
    ('A equipe é excepcional', '1'),
    ('O livro é incrivelmente inspirador', '1'),
    ('A paisagem é deslumbrante', '1'),
    ('O almoço foi maravilhoso', '1'),
    ('A peça de teatro foi emocionante', '1'),
    ('O esforço foi recompensado', '1'),
    ('A surpresa foi inesperada', '1'),
    ('O passeio foi divertido', '1'),
    ('A vista da montanha é espetacular', '1'),
    ('O sorvete é delicioso', '1'),
    ('A noite foi memorável', '1'),
    ('A viagem foi transformadora', '1'),
    ('O dia do casamento foi mágico', '1'),
    ('O nascer do sol é deslumbrante', '1'),
    ('A música me faz dançar', '1'),
    ('O presente foi surpreendente', '1'),
    ('A reunião foi produtiva', '1'),
    ('O pôr do sol é incrível', '1'),
    ('A apresentação foi envolvente', '1'),
    ('O espetáculo foi arrebatador', '1'),
    ('Ela é uma pessoa incrível', '1'),
    ('Estou me sentindo inspirado', '1'),
    ('O resultado foi surpreendente', '1'),
    ('A notícia é emocionante', '1'),
    ('A descoberta é incrível', '1'),
    ('O talento dele é notável', '1'),
    ('O piquenique foi memorável', '1'),
    ('O sorriso dela é cativante', '1'),
    ('O dia foi extremamente produtivo', '1'),
    ('A vista da montanha é impressionante', '1'),
    ('O sorvete é tentador', '1'),
    ('A noite estrelada é mágica', '1'),
    ('A surpresa foi inesquecível', '1'),
    ('A reunião foi altamente produtiva', '1'),
    ('Este restaurante é terrível', '0'),
    ('O clima hoje está péssimo', '0'),
    ('Detestei a música que tocou', '0'),
    ('Minhas férias foram terríveis', '0'),
    ('Ela é uma amiga insuportável', '0'),
    ('O por do sol é horrível', '0'),
    ('A comida estava péssima', '0'),
    ('O livro é desanimador', '0'),
    ('O abraço dela me faz mal', '0'),
    ('Eu perdi na loteria!', '0'),
    ('Este filme é horrível', '0'),
    ('A festa foi um desastre', '0'),
    ('Eu me sinto muito triste hoje', '0'),
    ('A aula foi improdutiva', '0'),
    ('Ele é um desastre', '0'),
    ('A natureza é terrível', '0'),
    ('A equipe perdeu o jogo', '0'),
    ('A arte é repugnante', '0'),
    ('O bolo está horrível', '0'),
    ('O novo carro é decepcionante', '0'),
    ('A apresentação foi terrível', '0'),
    ('O espetáculo foi entediante', '0'),
    ('Ela é uma pessoa detestável', '0'),
    ('Estou desanimado por você', '0'),
    ('Esta viagem foi decepcionante', '0'),
    ('O dia do casamento foi um pesadelo', '0'),
    ('A vista da montanha é desanimadora', '0'),
    ('O sorvete é ruim', '0'),
    ('A noite estrelada é feia', '0'),
    ('A surpresa foi horrível', '0'),
    ('A reunião foi improdutiva', '0'),
    ('O pôr do sol é terrível', '0'),
    ('A música me desagrada profundamente', '0'),
    ('O presente foi decepcionante', '0'),
    ('Este lugar é desanimador', '0'),
    ('Ela é uma pessoa desmotivadora', '0'),
    ('O show foi terrível', '0'),
    ('O ódio é horrível', '0'),
    ('O parque é desagradável', '0'),
    ('O livro é desinteressante', '0'),
    ('A comida é terrível', '0'),
    ('O filme é entediante', '0'),
    ('O nascer do sol é desanimador', '0'),
    ('Este jogo é entediante', '0'),
    ('A viagem foi decepcionante', '0'),
    ('O encontro foi péssimo', '0'),
    ('A amizade é desanimadora', '0'),
    ('O espetáculo é entediante', '0'),
    ('Ela é uma pessoa insuportável', '0'),
    ('Estou me sentindo amaldiçoado', '0'),
    ('O resultado foi terrível', '0'),
    ('A notícia é desanimadora', '0'),
    ('A descoberta é terrível', '0'),
    ('O talento dele é decepcionante', '0'),
    ('O piquenique foi horrível', '0'),
    ('O sorriso dela é desagradável', '0'),
    ('O dia foi incrivelmente improdutivo', '0'),
    ('A vista da montanha é decepcionante', '0'),
    ('O sorvete é horrível', '0'),
    ('A noite foi esquecível', '0'),
    ('A viagem foi desmotivadora', '0'),
    ('O dia do casamento foi um pesadelo', '0'),
    ('O nascer do sol é desanimador', '0'),
    ('A música me faz chorar', '0'),
    ('O presente foi desapontante', '0'),
    ('A reunião foi improdutiva', '0'),
    ('O pôr do sol é terrível', '0'),
    ('A apresentação foi desinteressante', '0'),
    ('O espetáculo foi entediante', '0'),
    ('Ela é uma pessoa insuportável', '0'),
    ('Estou me sentindo desanimado', '0'),
    ('O resultado foi decepcionante', '0'),
    ('A notícia é desanimadora', '0'),
    ('A descoberta é terrível', '0'),
    ('O talento dele é desanimador', '0'),
    ('O piquenique foi um desastre', '0'),
    ('O sorriso dela é irritante', '0'),
    ('O dia foi extremamente improdutivo', '0'),
    ('A vista da montanha é decepcionante', '0'),
    ('O sorvete é repugnante', '0'),
    ('A noite estrelada é horrível', '0'),
    ('A surpresa foi esquecível', '0'),
    ('A reunião foi altamente improdutiva', '0'),
    ('O pôr do sol é terrível', '0'),
    ('A música me irrita profundamente', '0'),
    ('O presente foi decepcionante', '0'),
    ('Este lugar é desagradável', '0'),
    ('Ela é uma pessoa desmotivadora', '0'),
    ('O show foi terrível', '0'),
    ('O ódio é horrível', '0'),
    ('O parque é desagradável', '0'),
    ('O livro é desinteressante', '0'),
    ('A comida é terrível', '0'),
    ('O filme é entediante', '0'),
    ('O nascer do sol é desanimador', '0'),
    ('Este jogo é entediante', '0'),
    ('A viagem foi decepcionante', '0'),
    ('O encontro foi péssimo', '0'),
    ('A amizade é desanimadora', '0'),
    ('O espetáculo é entediante', '0'),
    ('Ela é uma pessoa insuportável', '0'),
    ('Estou me sentindo amaldiçoado', '0'),
    ('O resultado foi terrível', '0'),
    ('A notícia é desanimadora', '0'),
    ('A descoberta é terrível', '0'),
    ('O talento dele é decepcionante', '0'),
    ('O piquenique foi horrível', '0'),
    ('O sorriso dela é desagradável', '0'),
    ('O dia foi incrivelmente improdutivo', '0'),
    ('A vista da montanha é decepcionante', '0'),
    ('O sorvete é horrível', '0'),
    ('A noite foi esquecível', '0'),
    ('A viagem foi desmotivadora', '0'),
    ('O dia do casamento foi um pesadelo', '0'),
    ('O nascer do sol é desanimador', '0'),
    ('A música me faz chorar', '0'),
    ('O presente foi desapontante', '0'),
    ('A reunião foi improdutiva', '0'),
    ('O pôr do sol é terrível', '0'),
    ('A apresentação foi desinteressante', '0'),
    ('O espetáculo foi entediante', '0')
]

vectorizer = TfidfVectorizer(preprocessor=preprocess_text)
train_features = vectorizer.fit_transform([x[0] for x in train_data])
train_labels = [x[1] for x in train_data]
classifier = svm.SVC(kernel='linear')
classifier.fit(train_features, train_labels)


def predict_sentiment(sentence):
    sentence = preprocess_text(sentence)
    features = vectorizer.transform([sentence])
    sentiment = classifier.predict(features)[0]
    return sentiment


for i in range(0, 10000):
    text = predict_sentiment(input("Digite uma frase: "))
    print(text)
